# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3873c2f4c95a61cb786969d48e86a6eb1f0bfbb68cc26858593d4f93a70996ef9435b807ce595fe926e8bdc8b7b884eb639b6ec0c9ef07d5e93a367b7b5bd382

test:
  secret_key_base: 2aa2160406791c4df90ada20672d3781c8437b952c94d54e8fcab16220fec0f103ea247c51f10e98740aee43ed67413a9d4dace19c670238b104f74a0e89e983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
